[package]
name = "rust-test"
version = "0.1.0"
authors = ["Thomas Povinelli <tompov227@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"

[[bin]]
name = "rust-test"
path = "main.rs"
